
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ”Œ  Checkout"
        uses: actions/checkout@v2

      - name: "ðŸ”Œ  Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "ðŸ”¨ Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "ðŸ”¨ Get version"
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)
      - name: "ðŸ”¨ Publish aws cdk"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            AWS_CDK_VERSION=${{ steps.vars.outputs.version }}
          tags: slashgordon/aws-cdk:${{ steps.vars.outputs.version }},slashgordon/aws-cdk:latest
      - name: "ðŸš€ (Github) Release  ðŸš€"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.vars.outputs.version }}"
          prerelease: false
          title: "AWS-CDK Docker ${{ steps.vars.outputs.version }}"
          files: |
            Dockerfile
            VERSION